Repository tryber/sd-09-project-delivery-app, pull requests merged in 2021-09, with the labels that each got.

#188 [Main group 9][refatoração rotas]
  back-end/.eslintignore
  back-end/.gitignore
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/server.js
  back-end/src/database/controllers/ProductController.js
  back-end/src/database/controllers/UserController.js
  back-end/src/database/models/product.js
  back-end/src/database/services/ProductService.js
  back-end/src/database/services/UserService.js
  back-end/src/routes/loginRoute.js
  back-end/src/routes/productRoute.js
  back-end/src/routes/registerRoute.js
  back-end/src/routes/saleRoute.js
  data-testids.md
  front-end/src/components/cardOrder/index.jsx
  front-end/src/components/navbar/index.jsx
  front-end/src/components/statusOrder/index.jsx
Labels: Code Review

#245 [MAIN GROUP 7][FEAT][NAVBAR]
  front-end/src/App.js
  front-end/src/Components/NavBar.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
  front-end/src/pages/Register.jsx
Labels: Code Review

#248 Main group 8.req 2.back end register
  __tests__/config/utils/resetDB.js
  back-end/src/api/controllers/registerController.js
  back-end/src/api/middlewares/encryptPassword.js
  back-end/src/api/middlewares/registerValidator.js
  back-end/src/api/router/router.js
  back-end/src/api/services/loginService.js
  back-end/src/api/services/registerService.js
  back-end/src/api/utils/errorTypes.js
  data-testids.md
  package-lock.json
  package.json
Labels: Code Review

#244 [MAIN GROUP 13] [API] [FEAT] [GET SELLERS]
  back-end/src/api/controllers/userController.js
  back-end/src/api/routes.js
  back-end/src/api/services/userService.js
  front-end/src/hooks/useRegister.js
Labels: Code Review

#252 [MAIN GROUP 7][FEAT][API][FIND SALE BY USER ID]
  back-end/doc.txt
  back-end/src/api/Router/saleRoutes.js
  back-end/src/controllers/Sale.js
  back-end/src/database/models/sale.js
  back-end/src/services/Sale.js
  front-end/package.json
  front-end/src/Components/NavBar.jsx
  front-end/src/Components/ProductCard.jsx
  front-end/src/pages/Products.jsx
Labels: Code Review

#259 [Main group 16][Requisitos 17 ao 21 & Fix 15]
  back-end/src/api/server.js
  back-end/src/database/migrations/20210825213343-create-sale.js
  back-end/src/services/loginService.js
  front-end/src/App.js
  front-end/src/Components/Organisms/LoginForm.js
  front-end/src/Components/newComponents/CartButton.jsx
  front-end/src/Components/newComponents/NabBar.jsx
  front-end/src/Components/newComponents/OrderForms.jsx
  front-end/src/Components/newComponents/OrderTable.jsx
  front-end/src/Components/newComponents/productCard/index.jsx
  front-end/src/Contexts/CartContext.jsx
  front-end/src/Pages/Checkout.jsx
  front-end/src/Pages/index.js
  front-end/src/contexts/CartContext.js
  front-end/src/services/api.js
  front-end/src/services/userRegister.js
  front-end/src/styles/Checkout.css
Labels: Code Review

#260 [MAIN GROUP 13] [API] [FEAT] [UPDATE SALE STATUS]
  back-end/src/api/controllers/saleController.js
  back-end/src/api/routes.js
  back-end/src/api/services/saleService.js
  back-end/src/api/services/utils/saleValidate.js
Labels: Code Review

#242 [main group 4][front][feat][customer checkout]
  back-end/src/api/controllers/sale.js
  back-end/src/api/controllers/user.js
  back-end/src/api/services/sale.js
  back-end/src/database/migrations/20210825201315-create-sale.js
  back-end/src/database/models/Sale.js
  back-end/src/database/models/SalesProduct.js
  back-end/src/database/models/User.js
  front-end/src/components/Customer/CheckoutTable.js
  front-end/src/components/Customer/ProductCard.js
  front-end/src/context/CustomerContext.js
  front-end/src/data/ButtonOptions.js
  front-end/src/data/InputOptions.js
  front-end/src/pages/Customer/Checkout.js
  front-end/src/pages/Customer/Products.js
  front-end/src/pages/Login.js
  front-end/src/pages/Register.js
  front-end/src/services/api.js
Labels: In Development, Code Review

#231 Main group 15 feat customerproducts
  back-end/src/controllers/imagesController.js
  back-end/src/controllers/productsController.js
  back-end/src/controllers/routes/router.js
  back-end/src/images/antarctica_pilsen_300ml.jpg
  back-end/src/images/becks_330ml.jpg
  back-end/src/images/becks_600ml.jpg
  back-end/src/images/brahma_600ml.jpg
  back-end/src/images/brahma_duplo_malte_350ml.jpg
  back-end/src/images/da_mantiqueira_red_ale.jpg
  back-end/src/images/heineken_600ml.jpg
  back-end/src/images/rockGlass.svg
  back-end/src/images/skol_269ml.jpg
  back-end/src/images/skol_beats_senses_269ml.jpg
  back-end/src/images/skol_beats_senses_313ml.jpg
  back-end/src/images/skol_lata_350ml.jpg
  back-end/src/images/stella_artois_275ml.jpg
  back-end/src/middlewares/mdwImage.js
  back-end/src/middlewares/mdwProducts.js
  back-end/src/services/image.js
  back-end/src/services/login.js
  back-end/src/services/products.js
  data-testids.md
  front-end/src/App.js
  front-end/src/components/cards/Cards.jsx
  front-end/src/components/navBar/NavBar.jsx
  front-end/src/components/navBar/navBar.style.js
  front-end/src/context/GlobalContext.js
  front-end/src/context/GlobalProvider.js
  front-end/src/data/mockedData.js
  front-end/src/pages/custumerProducts/CustumerProducts.jsx
  front-end/src/pages/custumerProducts/custumerProducts.style.js
  front-end/src/pages/login/Login.jsx
  front-end/src/pages/register/Register.jsx
  front-end/src/services/loginAPI.js
  front-end/src/services/products.js
Labels: Code Review

#284 [MAIN GROUP 7][FIX][API][FIND SALE BY USER ID]
  back-end/doc.txt
  back-end/src/api/Router/saleRoutes.js
  back-end/src/controllers/Sale.js
Labels: Code Review

#273 [MAIN GROUP 13][FEAT][CLIENT PRODUCTS PAGE]
  back-end/package-lock.json
  back-end/src/database/config/config.js
  back-end/src/database/seeders/20210826132039-products.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/components/Header.js
  front-end/src/components/ProductCard.js
  front-end/src/context/Provider.js
  front-end/src/context/customerContext.js
  front-end/src/context/customerProvider.js
  front-end/src/hooks/useLogin.js
  front-end/src/hooks/useProducts.js
  front-end/src/hooks/utils/useTotalPrice.js
  front-end/src/pages/ClientProducts.js
  front-end/src/pages/Login.js
  front-end/src/pages/Routes.js
  package-lock.json
  package.json
Labels: Code Review

#291 Main group 8.back end customer product
  back-end/src/api/controllers/customerController.js
  back-end/src/api/controllers/registerController.js
  back-end/src/api/middlewares/jwtValidator.js
  back-end/src/api/middlewares/readSecret.js
  back-end/src/api/middlewares/tokenGenerator.js
  back-end/src/api/router/router.js
  back-end/src/api/services/customerService.js
  back-end/src/api/utils/errorTypes.js
  back-end/src/database/models/product.js
  front-end/src/services/api/index.js
Labels: Code Review

#293 [main group 4][front][development][customer-order-details]
  back-end/src/api/services/sale.js
  back-end/src/api/services/user.js
  front-end/src/App.js
  front-end/src/components/Customer/OrderDetailsTable.js
  front-end/src/pages/Customer/OrdersDetails.js
  front-end/src/pages/Home.js
  front-end/src/pages/Login.js
  front-end/src/pages/Register.js
  front-end/src/pages/index.js
Labels: In Development

#300 [MAIN GROUP 7][FEAT][REQ11 - REQ16]
  back-end/package-lock.json
  back-end/public/images/antarctica_pilsen_300ml.jpg
  back-end/public/images/becks_330ml.jpg
  back-end/public/images/becks_600ml.jpg
  back-end/public/images/brahma_600ml.jpg
  back-end/public/images/brahma_duplo_malte_350ml.jpg
  back-end/public/images/da_mantiqueira_red_ale.jpg
  back-end/public/images/heineken_600ml.jpg
  back-end/public/images/skol_269ml.jpg
  back-end/public/images/skol_beats_senses_269ml.jpg
  back-end/public/images/skol_beats_senses_313ml.jpg
  back-end/public/images/skol_lata_350ml.jpg
  back-end/public/images/stella_artois_275ml.jpg
  back-end/src/api/app.js
  front-end/package-lock.json
  front-end/src/Components/NavBar.jsx
  front-end/src/Components/ProductCard.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
Labels: Code Review

#303 [MAIN GROUP 13][FEAT] [CHECKOUT PAGE]
  back-end/package-lock.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/components/CheckoutItem.js
  front-end/src/components/CheckoutTable.js
  front-end/src/components/ProductCard.js
  front-end/src/context/customerProvider.js
  front-end/src/hooks/useLogin.js
  front-end/src/hooks/useOrder.js
  front-end/src/hooks/useSellers.js
  front-end/src/pages/Checkout.js
  front-end/src/pages/ClientProducts.js
  front-end/src/pages/Routes.js
  package-lock.json
  package.json
Labels: Code Review

#306 [main-group-4][front][feat][order-pages]
  back-end/src/database/migrations/20210825200940-create-product.js
  back-end/src/database/migrations/20210825201315-create-sale.js
  back-end/src/database/models/Product.js
  back-end/src/database/models/Sale.js
  front-end/src/components/Navbar.js
  front-end/src/pages/Customer/Orders.js
  front-end/src/pages/Customer/OrdersDetails.js
  front-end/src/pages/Login.js
Labels: Code Review

#316 [Main Group 4][Front][admin-page]
  back-end/src/api/app.js
  back-end/src/api/controllers/user.js
  back-end/src/api/services/user.js
  front-end/src/components/Admin/ManageUserTable.js
  front-end/src/data/ButtonOptions.js
  front-end/src/data/InputOptions.js
  front-end/src/pages/Admin/Manage.js
  front-end/src/pages/Customer/Orders.js
  front-end/src/pages/Login.js
  front-end/src/pages/Register.js
  front-end/src/services/api.js
Labels: In Development

#321 [Main Group 4][fix][date and price formats]
  front-end/src/components/Customer/CheckoutTable.js
  front-end/src/components/Customer/OrderDetailsTable.js
  front-end/src/components/Customer/ProductCard.js
  front-end/src/components/Seller/OrderDetailsTable.js
  front-end/src/data/ButtonOptions.js
  front-end/src/pages/Customer/Checkout.js
  front-end/src/pages/Customer/Orders.js
  front-end/src/pages/Customer/OrdersDetails.js
  front-end/src/pages/Customer/Products.js
  front-end/src/pages/Seller/Orders.js
  front-end/src/pages/Seller/OrdersDetails.js
  front-end/src/utils/creators.js
  front-end/src/utils/format.js
Labels: enhancement, Code Review

#327 initial commit
  front-end/src/pages/Customer/Orders.js
  front-end/src/pages/Customer/OrdersDetails.js
  front-end/src/pages/Seller/Orders.js
  front-end/src/pages/Seller/OrdersDetails.js
Labels: Code Review

#336 Main group 8.back end customer orders
  __tests__/config/utils/resetDB.js
  back-end/package-lock.json
  back-end/src/api/controllers/customerController.js
  back-end/src/api/controllers/registerController.js
  back-end/src/api/services/customerService.js
  back-end/src/api/utils/errorTypes.js
  back-end/src/database/models/sale.js
  front-end/package-lock.json
  package-lock.json
Labels: Code Review

#335 [Main Group 4][Front][Feat][Admin Pages]
  front-end/src/components/Admin/ManageUserTable.js
  front-end/src/pages/Admin/Manage.js
  front-end/src/services/api.js
Labels: Code Review

#310 Main group 8 validacao
  back-end/package-lock.json
  back-end/src/api/controllers/registerController.js
  back-end/src/api/middlewares/jwtValidator.js
  back-end/src/api/services/loginService.js
  back-end/src/api/services/registerService.js
  back-end/src/api/utils/filterUserData.js
  back-end/src/api/utils/readSecret.js
  back-end/src/api/utils/tokenGenerator.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/Pages/LoginPage/index.js
  front-end/src/Pages/RegisterPage/index.js
  front-end/src/Routes/index.js
  front-end/src/Routes/paths.js
  front-end/src/Routes/redirectByRole.js
  front-end/src/Services/Api/index.js
  front-end/src/Services/Auth/index.js
  front-end/src/context/index.js
  front-end/src/hooks/useLoginApi.js
  front-end/src/hooks/useLoginInfo.js
  front-end/src/hooks/useRegisterApi.js
  front-end/src/hooks/useRegisterInfo.js
  front-end/src/services/api/index.js
  front-end/src/utils/decodeUserInfo.js
  front-end/src/utils/handlers.js
  front-end/src/utils/storage.js
  front-end/src/utils/validateInfo.js
  package-lock.json
Labels: Code Review

#350 [Main Group 2] [feat] checkout page - db integration
  back-end/src/api/app.js
  back-end/src/api/controllers/sales.js
  back-end/src/api/middlewares/authMiddleware.js
  back-end/src/api/utils/jwtfunctions.js
  front-end/src/components/CheckoutTable.jsx
  front-end/src/components/ConfirmOrderButton.jsx
  front-end/src/components/InputAddress.jsx
  front-end/src/components/InputAddressNumber.jsx
  front-end/src/components/OrderAddress.jsx
  front-end/src/components/OrderCard.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/SellerSelect.jsx
  front-end/src/components/navBarCustomer.jsx
  front-end/src/context/ProductsProvider.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/CustomersOrders.jsx
  front-end/src/pages/LoginPage.jsx
  front-end/src/pages/customerProducts.jsx
  front-end/src/services/api.js
  front-end/src/styles/CustomersOrders.css
  front-end/src/styles/checkout.css
  front-end/src/styles/customerProducts.css
Labels: Code Review

#364 [Main Group 4][Requisitos 32 à 36]
  back-end/src/api/app.js
  back-end/src/api/controllers/login.js
  back-end/src/api/controllers/product.js
  back-end/src/api/controllers/sale.js
  back-end/src/api/controllers/user.js
  back-end/src/api/middlewares/Error.js
  back-end/src/api/middlewares/JoiValidate.js
  back-end/src/api/middlewares/validateAdmin.js
  back-end/src/api/middlewares/validateToken.js
  back-end/src/api/middlewares/validators.js
  back-end/src/api/routes/login.js
  back-end/src/api/routes/product.js
  back-end/src/api/routes/sale.js
  back-end/src/api/routes/user.js
  back-end/src/api/server.js
  back-end/src/api/services/generateToken.js
  back-end/src/api/services/product.js
  back-end/src/api/services/sale.js
  back-end/src/api/services/user.js
  back-end/src/api/utils/JoiSchemas.js
  back-end/src/api/utils/generateError.js
  front-end/src/components/Seller/Navbar.js
  front-end/src/components/index.js
  front-end/src/context/LoginContext.js
  front-end/src/context/index.js
  front-end/src/pages/Admin/Manage.js
  front-end/src/pages/Customer/Checkout.js
  front-end/src/pages/Customer/Orders.js
  front-end/src/pages/Customer/OrdersDetails.js
  front-end/src/pages/Customer/Products.js
  front-end/src/pages/Login.js
  front-end/src/pages/Register.js
  front-end/src/pages/Seller/Orders.js
  front-end/src/pages/Seller/OrdersDetails.js
  front-end/src/services/api.js
  front-end/src/utils/checkFormats.js
  front-end/src/utils/creators.js
  front-end/src/utils/validateEmail.js
  front-end/src/utils/validationNumbers.js
Labels: Code Review

#372 [UPDATE][REQ 21][BACK END][Checkout]
  __tests__/config/utils/resetDB.js
  back-end/package-lock.json
  back-end/src/api/controllers/customerController.js
  back-end/src/api/services/customerService.js
  back-end/src/api/services/loginService.js
  back-end/src/api/services/registerService.js
  back-end/src/api/utils/encryptPassword.js
  front-end/package-lock.json
  front-end/src/services/auth/index.js
  package-lock.json
  package.json
Labels: Code Review

#371 [Main Group 4][front][Customer-Seller Socket-io]
  back-end/src/api/app.js
  front-end/src/pages/Customer/Orders.js
  front-end/src/pages/Customer/OrdersDetails.js
  front-end/src/pages/Seller/Orders.js
  front-end/src/pages/Seller/OrdersDetails.js
Labels: Code Review

#365 [MAIN GROUP 6][FRONT & BACK][FEAT][TESTS]
  back-end/package-lock.json
  back-end/package.json
  back-end/src/database/migrations/20210825210227-create-sale.js
  back-end/src/database/migrations/20210825214025-create-sales-product.js
  back-end/src/tests/login.test.js
  front-end/src/tests/App.test.js
  front-end/src/tests/Login.test.js
  front-end/src/tests/Products.test.js
  front-end/src/tests/Register.test.js
  front-end/src/tests/renderWithRouter.js
  package-lock.json
Labels: Code Review

#358 [MAIN-GOUP-15][INTEGRATION]
  __tests__/end-to-end/05customer_orders.test.js
  back-end/src/controllers/routes/router.js
  back-end/src/controllers/updateSaleController.js
  back-end/src/database/models/sales.js
  back-end/src/database/seeders/20210831191835-sales.js
  back-end/src/database/seeders/20210831195243-salesProducts.js
  back-end/src/images/20210831191835-sales.js
  back-end/src/images/20210831195243-salesProducts.js
  back-end/src/middlewares/mdwUpdate.js
  back-end/src/services/createSale.js
  back-end/src/services/sellerOrders.js
  back-end/src/services/update.js
  front-end/src/App.js
  front-end/src/components/cards/Cards.jsx
  front-end/src/components/navBar/NavBar.jsx
  front-end/src/components/orders/Details.jsx
  front-end/src/components/sales/Sales.jsx
  front-end/src/pages/login/Login.jsx
  package-lock.json
Labels: In Development

#389 Main group 2 feat sockets
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/server.js
  back-end/src/api/sockets/deliveryApp.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/context/ProductsProvider.jsx
  front-end/src/pages/Admin.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/CustomersOrders.jsx
  front-end/src/pages/LoginPage.jsx
  front-end/src/pages/OrderDetails.jsx
  front-end/src/pages/SellerOrderDetails.jsx
  front-end/src/pages/SellerOrders.jsx
Labels: Code Review

#393 [MAIN GROUP 13] [FRONT] [FEAT] [ORDERS]
  back-end/src/api/services/saleService.js
  front-end/src/components/CheckoutForm/index.js
  front-end/src/components/Header.js
  front-end/src/components/OrderCard/OrderCard.css
  front-end/src/components/OrderCard/index.jsx
  front-end/src/components/OrderHeader/index.js
  front-end/src/context/sellerContext.js
  front-end/src/context/sellerProvider.js
  front-end/src/hooks/useLogin.js
  front-end/src/hooks/useOrderList.js
  front-end/src/pages/CustomerOrder.js
  front-end/src/pages/Login.js
  front-end/src/pages/NotFound.js
  front-end/src/pages/OrderDetail.js
  front-end/src/pages/Orders.js
  front-end/src/pages/Routes.js
  front-end/src/pages/SellerOrder.js
  front-end/src/utils/helpers.js
Labels: Code Review

#397 [MAIN GROUP 13] [FRONT] [FIX] [ROUTES /seller/orders and /customer/orders]
  front-end/src/pages/Routes.js
Labels: Code Review

#422 [Group 8] Seller flow
  front-end/src/components/molecules/OrderButtonGroup.jsx
  front-end/src/components/organisms/OrderCard.jsx
  front-end/src/components/organisms/OrderInfo.jsx
  front-end/src/components/organisms/OrderStatusBar.jsx
  front-end/src/context/CustomRoleProvider.jsx
  front-end/src/hooks/useDetectPage.js
  front-end/src/hooks/useOrderStatus.js
  front-end/src/pages/AdmPage/index.js
  front-end/src/pages/index.js
  front-end/src/pages/seller/OrderDetails/index.jsx
  front-end/src/pages/seller/Orders/index.jsx
  front-end/src/routes/index.js
  front-end/src/routes/paths.js
  front-end/src/routes/redirectByRole.js
  front-end/src/utils/getPageItemsByRole.js
  front-end/src/utils/getTestIds.js
  front-end/src/utils/testIds.js
Labels: Code Review

#430 [Main group 6][Atualização][Req 45]
  back-end/package-lock.json
  back-end/package.json
  front-end/.stylelintrc.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/Cart/Cart.css
  front-end/src/Cart/Cart.js
  front-end/src/components/NavBar.css
  front-end/src/components/ProductsCard.css
  front-end/src/css/login.css
  front-end/src/pages/Admin.css
  front-end/src/pages/Admin.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.css
  front-end/src/tests/Admin.test.js
  package-lock.json
  package.json
Labels: Code Review
